remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ICFP Contest 2022
description: The webpage for the ICFP Contest 2022 that will take place between 30th of August and 1st of September! 
